# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory:
        #     memory:
        #         users:
        #             user:
        #                 password: userpass
        #                 roles: 'ROLE_USER'
        #             admin:
        #                 password: adminiscool
        #                 roles: 'ROLE_ADMIN'
        fos_userbundle:
            id: fos_user.user_provider.username
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
        
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext        
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_SUPER_MOD_ADMIN: [ROLE_SUPER_ADMIN]

    firewalls:
        # # disables authentication for assets and the profiler, adapt it according to your needs
        # # dev:
        # #     pattern: ^/(_(profiler|wdt)|css|images|js)/
        # #     security: false

        # # default:
        # #     anonymous: ~
        # #     http_basic: ~
        # #     # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
        
        # login_firewall:
        #     pattern:   ^/login$
        #     anonymous: ~
        main:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
                provider: fos_userbundle
            logout:
                path: /logout
                target: /
            anonymous: ~
        
        # main:
        #     #anonymous: ~
        #     # activate different ways to authenticate
        #     pattern:    ^/
        #     http_basic: ~
        #     provider: our_db_provider

        #     # form_login: ~
        #     # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        #     context: user            
        #   # pattern: ^/
        #     form_login:
        #         provider: fos_userbundle
        #         csrf_token_generator: security.csrf.token_manager
        #         login_path: login
        #         check_path: login

        #     logout: true

        #     anonymous:    true
        
       # admin:
        #    context:            user
         #   logout:
          #      path:   /logout
           #     target: /
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        # - { path: ^/article/, role: ROLE_USER }
        # - { path: ^/category/, role: ROLE_USER }
        

